Create Table VIAGEM (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DATASAIDA varchar(10),
    DESTINO varchar(255),
    PRECO real,
    NUMEROMAXIMO integer,
    PASSAGEIROS integer
);

Create Table TICKET (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDVIAGEM INTEGER,
    IDLOGIN INTEGER
);