/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controle.Evento;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author infotv
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        Bottom = new javax.swing.JPanel();
        telaAcesso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        INICIO_login = new javax.swing.JTextField();
        INICIO_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        cadastraCarro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CADASTRA_marca = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CADASTRA_modelo = new javax.swing.JTextField();
        CADASTRA_placa = new javax.swing.JTextField();
        CADASTRA_proprietario = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        telaInicial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TELAINICIAL_tabelaCarros = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nVagas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bottom.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de estacionamento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha");

        INICIO_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIO_senhaActionPerformed(evt);
            }
        });

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaAcessoLayout = new javax.swing.GroupLayout(telaAcesso);
        telaAcesso.setLayout(telaAcessoLayout);
        telaAcessoLayout.setHorizontalGroup(
            telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAcessoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaAcessoLayout.createSequentialGroup()
                        .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(INICIO_login)
                                .addComponent(INICIO_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        telaAcessoLayout.setVerticalGroup(
            telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAcessoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(INICIO_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(INICIO_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        Bottom.add(telaAcesso, "telaAcesso");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Marca");

        CADASTRA_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ford", "Fiat", "GM", "Volkswagen" }));
        CADASTRA_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRA_marcaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Modelo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Placa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Proprietario");

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastraCarroLayout = new javax.swing.GroupLayout(cadastraCarro);
        cadastraCarro.setLayout(cadastraCarroLayout);
        cadastraCarroLayout.setHorizontalGroup(
            cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastraCarroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastraCarroLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastraCarroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CADASTRA_marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CADASTRA_modelo)
                            .addComponent(CADASTRA_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastraCarroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CADASTRA_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastraCarroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        cadastraCarroLayout.setVerticalGroup(
            cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastraCarroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CADASTRA_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CADASTRA_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CADASTRA_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CADASTRA_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(cadastraCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Bottom.add(cadastraCarro, "cadastraCarro");

        TELAINICIAL_tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Placa", "Marca", "Modelo", "Prop"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TELAINICIAL_tabelaCarros);
        if (TELAINICIAL_tabelaCarros.getColumnModel().getColumnCount() > 0) {
            TELAINICIAL_tabelaCarros.getColumnModel().getColumn(0).setResizable(false);
            TELAINICIAL_tabelaCarros.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Baixa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vagas");

        nVagas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nVagas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nVagas.setText(Evento.nVagasRestantes());

        javax.swing.GroupLayout telaInicialLayout = new javax.swing.GroupLayout(telaInicial);
        telaInicial.setLayout(telaInicialLayout);
        telaInicialLayout.setHorizontalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaInicialLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nVagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        telaInicialLayout.setVerticalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaInicialLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaInicialLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nVagas)))
                .addGap(18, 18, 18)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Bottom.add(telaInicial, "telaInicial");

        jMenu1.setText("Arquivo");

        menu_sair.setText("Sair");
        menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sairActionPerformed(evt);
            }
        });
        jMenu1.add(menu_sair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ajuda");

        jMenuItem2.setText("Instruções");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bottom.getAccessibleContext().setAccessibleName("bottom_panel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "telaAcesso");
    }//GEN-LAST:event_menu_sairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.INICIO_login.getText().equals("") && this.INICIO_senha.getText().equals("")) {
            Alerta.mostraString("Login e senha devem ser preenchidos");
        } else if (Evento.entrar(this.INICIO_login.getText(), this.INICIO_senha.getText())) {
            this.atualizaTabela();
            this.limpaCampos();

            CardLayout cl = (CardLayout) (Bottom.getLayout());
            cl.show(Bottom, "telaInicial");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void INICIO_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIO_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INICIO_senhaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.limpaCampos();
        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "cadastraCarro");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CADASTRA_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRA_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CADASTRA_marcaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (this.CADASTRA_modelo.getText().equals("") && this.CADASTRA_placa.getText().equals("") && this.CADASTRA_proprietario.getText().equals("")) {
            Alerta.mostraString("Todos os campos devem ser preenchidos");
        } else {
            Evento.cadastra_vaga(CADASTRA_marca.getSelectedIndex(), this.CADASTRA_modelo.getText(), this.CADASTRA_placa.getText(), this.CADASTRA_proprietario.getText());
            this.atualizaTabela();
            this.limpaCampos();

            CardLayout cl = (CardLayout) (Bottom.getLayout());
            cl.show(Bottom, "telaInicial");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Evento.baixa((String) TELAINICIAL_tabelaCarros.getValueAt(TELAINICIAL_tabelaCarros.getSelectedRow(), 1));
            this.atualizaTabela();
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
            Alerta.mostraString("Selecione algum carro para dar baixa");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "telaInicial");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Alerta.mostraString(
                "Este sistema é parte de um exercicio a ser desenvolvido pela turma da disciplina\n"
                + "'Desenvolvimento de Sistemas Orientado a Objetos II' da Universidade Federal de Santa Catarina\n"
                + " no Semestre 2014/1. \n\n"
                + "Desenvolvedor/Aluno: Elizeu Santos Madeira - Mat: 10101181\n"
                + "Email: elizeu.madeira@gmail.com");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Alerta.mostraString(
                "Acessar com login 'Admin' e Senha 'Admin'\n\n"
                + "Ao acessar o sistema, você visualizará a tabela com todos os carros cadastrados\n"
                + "Não há limite para cadastro de carros, porém, há apenas 20 vagas no estacionamento\n"
                + "que pode ser visualizado ao lado da tabela principal. Contam somente os carros com status 'In'\n\n"
                + "Abaixo ha um botão 'Atualizar', para que o sistema redesenhe a tabela e ao lado o botão \n"
                + "'Cadastrar, para cadastrar um novo carro, lembrando que a nao é possivel cadastrar veiculos' \n"
                + "com a mesma placa \n");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void atualizaTabela() {
        //reinicia a tabela com os produtos
        TELAINICIAL_tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
                Evento.getArrayEstacionamento(),
                new String[]{
                    "Status", "Placa", "Marca", "Modelo", "Prop"
                }) {

                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[columnIndex];
                    }
                });
        TELAINICIAL_tabelaCarros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TELAINICIAL_tabelaCarros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TELAINICIAL_tabelaCarros);
        TELAINICIAL_tabelaCarros.getAccessibleContext().setAccessibleName("");

        nVagas.setText(Evento.nVagasRestantes());
    }

    public void acrescentaLinhaTabelaVenda(Object[] linhaTabelaVenda) {
        try {
            DefaultTableModel model = (DefaultTableModel) this.TELAINICIAL_tabelaCarros.getModel();
            model.addRow(linhaTabelaVenda);
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
            System.err.println(e.getMessage());
        }

    }

    public void limpaCampos() {
        this.CADASTRA_modelo.setText("");
        this.CADASTRA_placa.setText("");
        this.CADASTRA_proprietario.setText("");
        this.INICIO_login.setText("");
        this.INICIO_senha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JComboBox CADASTRA_marca;
    private javax.swing.JTextField CADASTRA_modelo;
    private javax.swing.JTextField CADASTRA_placa;
    private javax.swing.JTextField CADASTRA_proprietario;
    private javax.swing.JTextField INICIO_login;
    private javax.swing.JPasswordField INICIO_senha;
    private javax.swing.JTable TELAINICIAL_tabelaCarros;
    private javax.swing.JPanel cadastraCarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_sair;
    private javax.swing.JLabel nVagas;
    private javax.swing.JPanel telaAcesso;
    private javax.swing.JPanel telaInicial;
    // End of variables declaration//GEN-END:variables
}
